### ISSUE TITLE
Item models are generated in a batch and not individually

### ISSUE THREAD

**Issue by Cart3r1234** [Deviouslrd/json-generator#5]
Unlike Blockmodels, when generating item models, you cannot generate _just_ a slab model, or just a stair model - Block, Slab, Pillar, and Stair are all generated at once

**Comment by Deviouslrd** [comment]
Take note that item models were made first, and i was so smart and decided to batch them together because they all used the same json file formats, and early on i thought it would be good to generate them all at once, but once i made checkboxes for all the other tabs, I now realise its not a viable option. Will be fixed soon.

**Comment by Deviouslrd** [comment]
Patched in 1.2
